<a href="https://colab.research.google.com/github/JisaVarghese/MachineLearning/blob/main/DecisionTree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import pydot 
from sklearn import tree
from IPython.display import Image  
from sklearn.externals.six import StringIO

In [7]:
df = pd.read_csv("CovidDensity.csv")
df.head()

OBJECTID  ORIGID  ...  SHAPE_Length   SHAPE_Area
0      6397       1  ...  3.193486e+05   2432351721
1      6398       2  ...  5.159545e+05   5575009911
2      6399       3  ...  1.013949e+06   8722541706
3      6400       4  ...  2.129949e+06  19529490886
4      6401       5  ...  2.145086e+06  14624041937

[5 rows x 17 columns]

In [8]:
df.shape

(572, 17)

In [ ]:
d = {'Low': 1, 'Medium': 2, 'High': 3} 

df['Covid Density'] = df['Covid Density'].map(d)
Target_Names = {'Low','Medium','High'}


In [18]:
X = df[['Lat', 'Long', 'IGEasting', 'IGNorthing']].values
y = df[['Covid Density']].values
y = Y.reshape(572)

print (X)


[[ 5.27168e+01 -6.83670e+00  2.78661e+05  1.63444e+05]
 [ 5.39878e+01 -7.29370e+00  2.46380e+05  3.04501e+05]
 [ 5.28917e+01 -8.98890e+00  1.33493e+05  1.82732e+05]
 ...
 [ 5.35524e+01 -7.42190e+00  2.38362e+05  2.55966e+05]
 [ 5.25164e+01 -6.50370e+00  3.01627e+05  1.41559e+05]
 [ 5.30205e+01 -6.34420e+00  3.11162e+05  1.97894e+05]]


In [19]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X,y)

In [23]:
Feature_Names = {'Lat','Long','IGEasting','IGNorthing'}
dot_data = StringIO()  
tree.export_graphviz(clf, out_file=dot_data,  
                         feature_names=Feature_Names)   
(graph,) = pydot.graph_from_dot_data(dot_data.getvalue())

Image(graph.create_png())

TypeError: ignored

In [ ]:
print (clf.predict([[60.96, -10.2, 257896, 512369]]))

#print (clf.predict([[1, 55000, 3, 100]]))